---
abstract: 'The great new Massprot!'
author:
  - 'David Ovelleiro, C<< <mass.proteomics at gmail.com> >>'
  - 'David Ovelleiro <mass.proteomics@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
  Module::Install: 0
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Massprot
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Massprot
  homepage: http://bioinformatika.github.io/massprot/
  license: http://www.apache.org/licenses/LICENSE-2.0
  repository: git://github.com/bioinformatika/massprot/Massprot.git
version: '0.01'
